version: '3'

services:
  zeppelin:
    build:
      context: .
      dockerfile: ./shared/resources/zeppelin/Dockerfile
    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_JAVA_OPTS: >-
        -Dspark.driver.memory=0.5g
        -Dspark.executor.memory=0.5g
      SPARK_SUBMIT_OPTIONS: >-
        --conf spark.driver.host=localhost
        --conf spark.driver.port=8081
      MASTER: local[*]
    ports:
      - 8080:8080
      - 8081:8081
      - 4040:4040
    volumes:
      - .:/app/
      - ./shared/resources/zeppelin/data:/usr/zeppelin/data
      - ./shared/resources/zeppelin/notebooks:/usr/zeppelin/notebook
